name = "minecontrol"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_flags = [ "streams_enable_constructors", "nodejs_compat" ]
compatibility_date = "2024-09-23"

[vars]
NODE_VERSION = "20.18.0"

[[d1_databases]]
binding="DB"
database_name="minecontrol"
database_id = "e9f759e6-5735-420c-874d-237b924d6d46"
migrations_dir = "drizzle"