name = "minecontrol"
pages_build_output_dir = ".svelte-kit/cloudflare"

[vars]
NODE_VERSION = "20.18.0"

[[d1_databases]]
binding="DB"
database_name="minecontrol"
database_id = "e9f759e6-5735-420c-874d-237b924d6d46"
migrations_dir = "drizzle"